version: '3'
services:
  astro-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai_blog-astro-app
    ports:
      - "3500:3500"
    volumes:
      - .:/app
      - ./src/content:/app/src/content
      - ./logs:/app/logs
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=production
      - TZ=UTC

volumes:
  blog-content:


